# Generated by Django 2.1.7 on 2019-06-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrancheL2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrancheL3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Département',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Adresse', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Bac', verbose_name='Bac')),
                ('BrancheL2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.BrancheL2', verbose_name='BrancheL2')),
                ('Département', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Département', verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Univérsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='univérsite',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='TypeEtablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.TypeEtablissement', verbose_name='TypeEtablissement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Univérsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Univérsite', verbose_name='Univérsite'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='département',
            name='Etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.Etablissement', verbose_name='Etablissement'),
        ),
        migrations.AddField(
            model_name='branchel2',
            name='BrancheL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuideEnseignement.BrancheL3', verbose_name='BrancheL3'),
        ),
    ]
